### ISSUE TITLE
is euclidian metric sufficient for measuring knn convergence?

### ISSUE THREAD

**Issue by dribnet** [minyoungg/platonic-rep#6]
If I understand correctly - one assumption of the current codebase/paper is that the best underlying measure of nearest neighbors across domains [is euclidian distance](https://github.com/minyoungg/platonic-rep/blob/d3da2a5ed5c0d1db3589cb56f37cda7c291ac397/metrics.py#L283) after optionally normalizing. However, the NLP community often uses cosine distance to measure similarity; for example the [MTEB benchmark](https://huggingface.co/blog/mteb) uses cosine almost exclusively as a distance measure across its eight internal tasks.

Is there a formal justification for this preference or comparison that shows the effect of using euclidian over other possibilities such as cosine (or manhattan distance, dot product, Mahalanobis, ...)?

My guess is that (like you show with the alignment metrics themselves!) most of these distance metrics are highly correlated with each other - but I'm not sure how to best support this claim. Or one potential way of demonstrating this would be to add support other distance metrics internally. Then one could either recreate a subset of your current results on cosine as well or perhaps more simply demonstrate that many known datasets usually have high mutual-knn scores *with themselves* across two different underlying metrics.

**Comment by dribnet** [comment]
After now thinking about this more: I believe I now see how the sorted order of the normalized vectors will in fact also match that expected by taking the cosine distance. So I will close this out, but feel free to correct / comment if I have this wrong! 😅

**Comment by ssnl** [comment]
Yes! The squared distance between normalized unit vectors is equivalent to cosine sim, up to a shift.
